# Generated by Django 4.2.7 on 2023-12-28 10:45

import apps.store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_options_order_total_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=apps.store.models.generate_order_id, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Створений'), (1, 'Підтверджений'), (2, 'Відправлений'), (3, 'Отриманий'), (4, 'Відмінений')], db_index=True, default=0),
        ),
    ]
