# Generated by Django 4.2.7 on 2024-03-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_id_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
